/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;


public class Main {
    
	/**
	 * Programa de saludo.
	 * 
	 * El programa debe solicitar al usuario que introduzca un nombre 
	 * que puede ser compuesto.
	 * Tras leerlo el programa saluda al nombre introducido.
	 * 
	 * Entrada/Salida de Ejemplo:
	 * P: Introduce tu nombre:
	 * U: Eduardo Serrano Luque
	 * P: Hola Eduardo Serrano Luque
	 * 
	 * @param args
	 */
    public static void main (String [] args) {
    	//TODO implementa aquí tu código.
    }
}
